from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('devices/', views.devices, name='devices'),
    path('configure/', views.configure, name='configure'),
    path('verify_configure/', views.verify_configure, name='verify_configure'),
    path('log/', views.log, name='log'),
    path('backup_devices/', views.backup_devices, name='backup_devices'),
    path('backup_logs/', views.backup_logs, name='backup_logs'),
    path('restore_devices/', views.restore_devices, name='restore_devices'),
    path('restore_logs/', views.restore_logs, name='restore_logs'),
    path('delete_devices/', views.delete_devices, name='delete_devices'),
    path('delete_logs/', views.delete_logs, name='delete_logs'),
    path('mikrotik_command_1/', views.mikrotik_command_1, name='mikrotik_command_1'),
    path('mikrotik_command_2/', views.mikrotik_command_2, name='mikrotik_command_2'),
    path('mikrotik_command_3/', views.mikrotik_command_3, name='mikrotik_command_3'),
    path('mikrotik_command_4/', views.mikrotik_command_4, name='mikrotik_command_4'),
    path('mikrotik_command_5/', views.mikrotik_command_5, name='mikrotik_command_5'),
    path('mikrotik_command_6/', views.mikrotik_command_6, name='mikrotik_command_6'),
    path('mikrotik_command_7/', views.mikrotik_command_7, name='mikrotik_command_7'),
    path('mikrotik_command_8/', views.mikrotik_command_8, name='mikrotik_command_8'),
    path('mikrotik_command_9/', views.mikrotik_command_9, name='mikrotik_command_9'),
    path('mikrotik_command_10/', views.mikrotik_command_10, name='mikrotik_command_10'),
    path('cisco_command_1/', views.cisco_command_1, name='cisco_command_1'),
    path('cisco_command_2/', views.cisco_command_2, name='cisco_command_2'),
    path('cisco_command_3/', views.cisco_command_3, name='cisco_command_3'),
    path('cisco_command_4/', views.cisco_command_4, name='cisco_command_4'),
    path('cisco_command_5', views.cisco_command_5, name='cisco_command_5'),
    path('cisco_command_6', views.cisco_command_6, name='cisco_command_6'),
    path('cisco_command_7', views.cisco_command_7, name='cisco_command_7'),
    path('cisco_command_8', views.cisco_command_8, name='cisco_command_8'),
    path('cisco_command_9', views.cisco_command_9, name='cisco_command_9'),
    path('cisco_command_10', views.cisco_command_10, name='cisco_command_10'),
    path('cisco_command_11', views.cisco_command_11, name='cisco_command_11'),
    path('cisco_command_12', views.cisco_command_12, name='cisco_command_12'),
    path('cisco_command_13', views.cisco_command_13, name='cisco_command_13'),
    path('cisco_command_14', views.cisco_command_14, name='cisco_command_14'),
    path('cisco_command_15', views.cisco_command_15, name='cisco_command_15'),
    # path('cisco_command_16', views.cisco_command_16, name='cisco_command_16'),
    path('config_ip/', views.config_ip, name='config_ip'),
    path('ping/', views.ping, name='ping'),
    path('tcl_ping/', views.tcl_ping, name='tcl_ping'),
    path('ssh_telnet/', views.ssh_telnet, name='ssh_telnet'),
]

